### ISSUE TITLE
[Question] Useless argument in IterativeStratification method

### ISSUE THREAD

**Issue by vfdev-5** [trent-b/iterative-stratification#1]
Hi, 
Variable k in the input of `IterativeStratification` method is not used, see [here](https://github.com/trent-b/iterative-stratification/blob/master/iterstrat/ml_stratifiers.py#L31). 
Maybe, it can be removed ?

PS: Thanks for implementation !

**EDIT:** I forked your repo and added a basic tests, fixed flake8 etc, [link](https://github.com/vfdev-5/iterative-stratification). If you are interested, I can submit a PR.

**Comment by trent-b** [comment]
Hi,
Thank you for your modifications especially for catching the extraneous variable k. Yes, please go ahead and submit a PR.

**Comment by trent-b** [comment]
Thank you for your commits.
