### ISSUE TITLE
Ability to set a custom fold proportions for MultilabelStratifiedKFold (pass "r" to IterativeStratification)

### ISSUE THREAD

**Issue by lopuhin** [trent-b/iterative-stratification#13]
For us it's useful to be able to set custom fold proportions when using ``MultilabelStratifiedKFold`` (essentially passing custom ``r`` to ``IterativeStratification``). It's easy enough to extend outside of the lib (only ``_make_test_folds`` needs to be copied), but I wonder if such a feature could be useful in the library itself, what do you think?

And thanks for a great library!

**Comment by trent-b** [comment]
Thank you for the suggestion. Could you share a use case where it would be useful to set custom fold proportions (pass a custom `r`)? I am not opposed to the idea as long as there is a use case for it. If you would like, you could submit a Pull Request with the suggested change along with some test code that I could review and merge. Thanks!

**Comment by lopuhin** [comment]
Thank you! The use-case is that we want to distribute a part of the dataset across a fold subset (n-1 folds in our case), and then distribute the rest of the dataset across all folds - setting ``r`` on the second step allows to get folds of equal sizes. The reason why we want to do that is rather specific, that's why is could be quite a marginal use-case.

**Comment by trent-b** [comment]
Closing since there has not been additional activity.
