### ISSUE TITLE
Is it possible to calculate the total number of all possible splits?

### ISSUE THREAD

**Issue by wusuowei60** [trent-b/iterative-stratification#16]
Love this repo, it spares me a lot effort.

Here is my question (or concern).

When we don't enforce any constraint when generating KFold, the number of all possible splits is the largest and simple to calculate.

When we only have one label and enforce the splits to be stratified, i.e. `StratifiedKFold`, this number drops, but normally will still be large enough to generate a diverse set of splits. Again, this number can be calculated with some simple combinatorics.

However, when stratification on multiple labels is enforced (the goal of this repo), things become more complicated and I am worried that if there are too much labels, say hundreds of them, there won't be too many possible splits that can satisfy the stratification constraint😟.

So my question is,

- Does my concern make sense?
- Can we calculate the total number of possibilities?

Looking forward to reply.

**Comment by trent-b** [comment]
Hi @wusuowei60, thank you for your question. I agree with your concern. The algorithm does its best to perform multilabel stratification as described by Sechidis et al., but it does not make any guarantees on the quality of its splits. Given the _iterative_ nature of the algorithm I am not entirely sure about the ability to calculate the total number of possibilities. I'll have to think on this and am open to suggestions on this calculation.

**Comment by trent-b** [comment]
Closing since there has not been additional activity.
