### ISSUE TITLE
Single split

### ISSUE THREAD

**Issue by sachinruk** [trent-b/iterative-stratification#21]
I was just wondering if it was possible to do a single split into training and testing without any folds. I see that there is a `BaseShuffleSplit` available, but when I try do `split = BaseShuffleSplit(2, test_size=0.1)` it chucks an error.

Just wondering what is the correct way to do it in here. The only work around I can see is to do something like:
```
mskf = MultilabelStratifiedKFold(n_splits=2, shuffle=True, random_state=0)
train_index, test_index = next(iter(mskf.split(X, y)))
```

**Comment by trent-b** [comment]
@sachinruk, I believe the following will work for you:

```from iterstrat.ml_stratifiers import MultilabelStratifiedShuffleSplit
import numpy as np

X = np.array([[1,2], [3,4], [1,2], [3,4], [1,2], [3,4], [1,2], [3,4]])
y = np.array([[0,0], [0,0], [0,1], [0,1], [1,1], [1,1], [1,0], [1,0]])

msss = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.1, random_state=0)
train_index, test_index = next(iter(msss.split(X, y)))```
