### ISSUE TITLE
Do we need X for `split`

### ISSUE THREAD

**Issue by sachinruk** [trent-b/iterative-stratification#23]
Forgive me if this is a dumb question, but if I understand this library correctly, the main aim is to look at correlations between the y's and somehow accomodate for that when stratifying. Is there any reason why we need the X variable as when splitting? eg. to get the indices we always have to do: `train_index, test_index = next(iter(msss.split(X, y)))`.

Thanks in advance.

**Comment by trent-b** [comment]
For non-stratified splitters, `scikit-learn` requires `X` to get the number of samples. For stratified splitters, `scikit-learn` requires `X` to get the number of samples for _compatibility purposes_ with the non-stratified splitters although there is no reason I can see that the required `y` could not be used to get the number of samples instead. For compatibility with `scikit-learn`, this `iterative-stratification` package adopts the same practice of requiring `X`.

**Comment by trent-b** [comment]
Closing since there has not been additional activity.
