### ISSUE TITLE
does this work with multiclass+multilabel targets?

### ISSUE THREAD

**Issue by dyhan316** [trent-b/iterative-stratification#27]
Thank you for your code! I was wondering, can I use this to do train/test split on multilabel + multi class targets? (your example seems to only show the binary case)

**Comment by trent-b** [comment]
Hi, this package does not directly support multiclass + multilabel splits. However, someone else recently asked the same question and seems to have come up with a workaround. See [here](https://github.com/trent-b/iterative-stratification/issues/26).

**Comment by dyhan316** [comment]
Thank you for your quick and concise reply! Just one quick question : is there a version for continuous variable stratification? Or should I do a work-around and discretize continuous target labels?

**Comment by trent-b** [comment]
Iterative stratification does not directly support continuous target labels. Discretizing continuous target variables, as you have suggested, would be the best workaround,

**Comment by dyhan316** [comment]
Thank you for your response:)
