### ISSUE TITLE
Adding importance to certain labels?

### ISSUE THREAD

**Issue by dyhan316** [trent-b/iterative-stratification#28]
Is there an option to add 'importance' to some labels?  

The use case would be : we want to classify only a single label (e.g. whether a person has Alzheimer or not), but want to make the stratified split as uniform as possible (i.e. each split has similar distributions of other metadata such as age and sex). However, because the current algorithm considers all labels equally, doing iterative stratification basically sacrifices the quality of the split for the target label to enhance the uniformness of other labels. Is there a way to tell the algorithm to focus on the target label, while putting less emphasis on the other labels? 

(I feel like this should be more of a question than an issue, but just wanted to listen to anybody's opinion :) )

**Comment by trent-b** [comment]
That's an interesting use case. I do not immediately see a way to do this with iterative stratification. I wonder if you could do something like splitting the data in half by the target label but then engage in a process where instances are iteratively swapped between the two splits to optimize the similarity of the multivariate input distributions. There are several ways to measure the similarity between two multivariate distributions. [Here](https://nannyml.readthedocs.io/en/stable/how_it_works/data_reconstruction.html) is one method (I haven't tried it myself).

**Comment by dyhan316** [comment]
Thank you for your detailed response!! :)
