### ISSUE TITLE
Numpy DeprecationWarning in IterativeStratification

### ISSUE THREAD

**Issue by alexrosenthal1098** [trent-b/iterative-stratification#31]
I have iterstrat version 0.1.7 and numpy version 1.26.4 installed, and when I call `MultilabelStratifiedShuffleSplit.split` I get a DeprecationWarning from numpy:
```
.../.venv/lib/python3.9/site-packages/iterstrat/ml_stratifiers.py:73: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    test_folds[sample_idx] = fold_idx
```
I believe it's because `fold_idx` in `IterativeStratification` has shape `(1,)` and numpy expects a scalar.

**Comment by trent-b** [comment]
Your observation about the shape of `fold_idx` may be correct, but I am unable to reproduce the DeprecationWarning by running the code below. I'm using Python 3.9, numpy 1.26.4, and iterstrat 0.1.7. Do you see the warning when you run the code below? If not, is there an example you can provide to help me reproduce the warning?

```from iterstrat.ml_stratifiers import MultilabelStratifiedShuffleSplit
import numpy as np

X = np.array([[1,2], [3,4], [1,2], [3,4], [1,2], [3,4], [1,2], [3,4]])
y = np.array([[0,0], [0,0], [0,1], [0,1], [1,1], [1,1], [1,0], [1,0]])

msss = MultilabelStratifiedShuffleSplit(n_splits=3, test_size=0.5, random_state=0)

for train_index, test_index in msss.split(X, y):
   print("TRAIN:", train_index, "TEST:", test_index)
   X_train, X_test = X[train_index], X[test_index]
   y_train, y_test = y[train_index], y[test_index]```

**Comment by alexrosenthal1098** [comment]
In lines 68-73 of `ml_stratifies.py':
```
fold_idx = np.where(c_folds == c_folds.max())[0]

if fold_idx.shape[0] > 1:
    fold_idx = fold_idx[random_state.choice(fold_idx.shape[0])]
    
test_folds[sample_idx] = fold_idx
```

The first assignment of fold_idx (with np.where) results in an ndarray, but if the if statement is entered it becomes a scalar. In the case that the if statement is not entered, the deprecation warning is raised in line 73. The example you created must've caused the if statement to be entered every time.

**Comment by alexrosenthal1098** [comment]
@trent-b the example you gave does produce a warning. Try adding this to the beginning:
```
import warnings
warnings.simplefilter('default')
```

**Comment by trent-b** [comment]
Thank you, @alexrosenthal1098! Using the 'default' warning filter allowed me to see the warning. I have modified the code to prevent the warning and have incremented the version to 0.1.8, which I've pushed to pypi.
