### ISSUE TITLE
Publication

### ISSUE THREAD

**Issue by miguelwon** [trent-b/iterative-stratification#7]
Does this package have a publication? I want to cite it in a research paper I'm currently working on.

**Comment by trent-b** [comment]
@miguelwon The package itself does not have a publication. It is an implementation of the algorithm described in the following paper:

Sechidis K., Tsoumakas G., Vlahavas I. (2011) On the Stratification of Multi-Label Data. In: Gunopulos D., Hofmann T., Malerba D., Vazirgiannis M. (eds) Machine Learning and Knowledge Discovery in Databases. ECML PKDD 2011. Lecture Notes in Computer Science, vol 6913. Springer, Berlin, Heidelberg.

I am not an author of the paper but please cite the paper. It would be great if you decide to provide the link to this github repo as a reference, but that is completely up to your discretion. Regardless of whether you reference this github repo, I'd love to read your paper. Please direct me to it when it is published. Thanks!
