### ISSUE TITLE
how to use iterative-stratification to split the dataset into train, validation and test set?

### ISSUE THREAD

**Issue by xyus** [trent-b/iterative-stratification#8]

**Comment by trent-b** [comment]
To create train, validation, and test sets, MultilabelStratifiedShuffleSplit can be called twice. For example, if the train, validation, and test sets should be 80%, 10%, and 10% respectively, then call MultilabelStratifiedShuffleSplit(n_splits=2, test_size=0.2) to get an 80% train set and a 20% "test" set. Next, call MultiLabelStratifiedShufflSplit(n_splits=2, test_size=0.5) with the "test" set to evenly split it into the validation and test sets.
